Loja-HorizonOS/Aplicativos/instalador-de-repositorios    Programas/Loja-HorizonOS/Aplicativos/
Loja-HorizonOS/Aplicativos/loja                          Programas/Loja-HorizonOS/Aplicativos/
Loja-HorizonOS/Aplicativos/loja-horizon-os.desktop       usr/share/applications/
Loja-HorizonOS/Logo/*                                    usr/share/pixmaps/
Loja-HorizonOS/Binário/*                                 usr/bin/
Loja-HorizonOS/Arquivos/                                 Programas/Loja-HorizonOS/